Add textbox messages
telerik/kendo-angular-messages pull request #130
Opened 2020-08-24 09:10 UTC by preslavapetrova1

2020-08-25 12:28 UTC, dtopalov requested changes
Capitalize all messages for consitency (**И**зчисти, **C**lear, ...)

2020-08-25 20:53 UTC, dtopalov commented
Also, perhaps add the title attribute of the HTML Input element as a translatable message similar to the clear button one, too.

2020-08-26 03:32 UTC, Raisolution commented
> Also, perhaps add the title attribute of the HTML Input element as a translatable message similar to the clear button one, too.

I don't think this will be intuitive as there is no specific default value we could set for it. Similarly to the placeholder text, it could be anything.

2020-08-26 03:33 UTC, Raisolution approved these changes

2020-08-26 08:33 UTC, dtopalov approved these changes

2020-08-26 10:30 UTC, merged