ColorPicker Messages
telerik/kendo-angular-messages pull request #157
Opened 2021-04-26 13:14 UTC by preslavapetrova1

2021-04-27 05:00 UTC, ipeshev requested changes

2021-04-27 06:22 UTC, tsvetomir approved these changes

2021-04-27 06:22 UTC, tsvetomir commented on messages/colorgradient/colorgradient.bg-BG.yml
> +    opacitySliderHandle: Добави Непрозрачност
Seems to use different casing than the rest of the messages.

2021-04-28 06:39 UTC, Raisolution approved these changes

2021-04-28 06:41 UTC, merged